version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
    command: ["php-fpm"]

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app

  # يمكنك إضافة قاعدة بيانات أو خدمات أخرى هنا حسب الحاجة.
