services:
  - name: laravel-app
    type: web
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 152.228.170.151:23930/f480e6a7

      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: diamntina	

      - key: DB_USERNAME
        value: diamntina	

      - key: DB_PASSWORD
        value: 62kwCYDbaHfYRHYN
    autoDeploy: true
